### ISSUE TITLE
https://apilist.tronscanapi.com/api/token_trc20/transfers-with-status?limit=1&start=0&trc20Id=TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4&address=

### ISSUE THREAD

**Issue by meemijung** [tron-list/token-list#294]
I’m {
    "contractMap":{
        "TDuZbZFtuCA177gtFBtD1jgivtUxR2RXRP":false,
        "TFP6WadqPJWbRcqi5GsK4xSCezUvznkb5j":false,
        "TDNQQNvRcacmJT44ETHDWf4Djo7y4TndPt":false
    },
    "tokenInfo":{
        "tokenId":"TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4",
        "tokenAbbr":"TUSD",
        "tokenName":"TrueUSD",
        "tokenDecimal":18,
        "tokenCanShow":1,
        "tokenType":"trc20",
        "tokenLogo":"https://static.tronscan.org/production/logo/TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4.png",
        "tokenLevel":"2",
        "issuerAddr":"TRX6Q82wMqWNbCCiLqejbZe43wk1h1zJHm",
        "vip":true
    },
    "page_size":1,
    "code":200,
    "data":[
        {
            "amount":"2531319816832000000000000",
            "status":0,
            "approval_amount":"0",
            "block_timestamp":1680520824000,
            "block":49969352,
            "from":"TV6MuMXfmLbBqPZvBHdwFsDnQeVfnmiuSi",
            "to":"TNXoiAJ3dct8Fjg4M9fkLFh9S2v9TXc32G",
            "hash":"09e76a0a358c205cfaaf366f340982024bdc9184c46fbad340003fdd34b8178d",
            "contract_address":"TUpMhErZL2fhh4sVNULAbNKLokS4GjC1F4",
            "confirmed":0,
            "contract_type":"TriggerSmartContract",
            "contractType":31,
            "revert":0,
            "contract_ret":"SUCCESS",
            "final_result":"SUCCESS",
            "event_type":"Transfer",
            "issue_address":"TRX6Q82wMqWNbCCiLqejbZe43wk1h1zJHm",
            "decimals":18,
            "token_name":"TrueUSD",
            "id"TFP6WadqPJWbRcqi5GsK4xSCezUvznkb5j
            "direction":1
        }
    ]
}

**Comment by Rchid-crypto** [comment]
TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

**Comment by Rchid-crypto** [comment]
الأصول محجوبة على هذه المعاملة TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t

**Comment by Hoangnam997** [comment]
UQCxGGAuwU7IgBkn2q9AgXHgqqnUW04RJ7_KxW18H_5u9XC4

**Comment by Hoangnam997** [comment]
UQAUxGo9p4B7ONERgx1uZevoyTY20SGzKMWHUDmVdHMHRQbz
